import type { ProductConfig } from '../types/game.types';

/**
 * Data-driven product catalog for VitaBalance.
 * Each entry defines a fruit or vegetable with its nutritional highlight,
 * seasonality, point value, and optional vitamin flags used by Level 2 objectives.
 *
 * Season values correspond to the central Argentina region (Buenos Aires, Córdoba, Santa Fe, Mendoza).
 * 'all' means available year-round.
 */
export const PRODUCTS: ProductConfig[] = [
  {
    id: 'naranja',
    name: 'Naranja',
    emoji: '🍊',
    nutrient: 'Vitamina C',
    season: 'invierno',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'banana',
    name: 'Banana',
    emoji: '🍌',
    nutrient: 'Potasio',
    season: 'all',
    points: 100,
    potassium: true,
  },
  {
    id: 'brocoli',
    name: 'Brócoli',
    emoji: '🥦',
    nutrient: 'Fibra y vitamina C',
    season: 'invierno',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'frutilla',
    name: 'Frutilla',
    emoji: '🍓',
    nutrient: 'Vitamina C y antioxidantes',
    season: 'primavera',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'espinaca',
    name: 'Espinaca',
    emoji: '🌿',
    nutrient: 'Hierro y ácido fólico',
    season: 'invierno',
    points: 100,
  },
  {
    id: 'zanahoria',
    name: 'Zanahoria',
    emoji: '🥕',
    nutrient: 'Vitamina A (betacaroteno)',
    season: 'all',
    points: 100,
  },
  {
    id: 'manzana',
    name: 'Manzana',
    emoji: '🍎',
    nutrient: 'Fibra',
    season: 'otono',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'tomate',
    name: 'Tomate',
    emoji: '🍅',
    nutrient: 'Licopeno y vitamina C',
    season: 'verano',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    emoji: '🥝',
    nutrient: 'Vitamina C y fibra',
    season: 'invierno',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'sandia',
    name: 'Sandía',
    emoji: '🍉',
    nutrient: 'Hidratación y licopeno',
    season: 'verano',
    points: 100,
  },
  {
    id: 'durazno',
    name: 'Durazno',
    emoji: '🍑',
    nutrient: 'Vitamina A y fibra',
    season: 'verano',
    points: 100,
  },
  {
    id: 'mandarina',
    name: 'Mandarina',
    emoji: '🍊',
    nutrient: 'Vitamina C',
    season: 'invierno',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'choclo',
    name: 'Choclo',
    emoji: '🌽',
    nutrient: 'Fibra y energía',
    season: 'verano',
    points: 100,
  },
  {
    id: 'zapallo',
    name: 'Zapallo',
    emoji: '🎃',
    nutrient: 'Vitamina A y fibra',
    season: 'otono',
    points: 100,
  },
  {
    id: 'pera',
    name: 'Pera',
    emoji: '🍐',
    nutrient: 'Fibra y potasio',
    season: 'otono',
    points: 100,
    potassium: true,
  },
  {
    id: 'limon',
    name: 'Limón',
    emoji: '🍋',
    nutrient: 'Vitamina C',
    season: 'invierno',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'pomelo',
    name: 'Pomelo',
    emoji: '🍈',
    nutrient: 'Vitamina C',
    season: 'invierno',
    points: 100,
    vitaminC: true,
  },
  {
    id: 'puerro',
    name: 'Puerro',
    emoji: '🧅',
    nutrient: 'Vitaminas del grupo B',
    season: 'invierno',
    points: 100,
  },
  {
    id: 'papa',
    name: 'Papa',
    emoji: '🥔',
    nutrient: 'Energía e hidratos',
    season: 'all',
    points: 100,
    potassium: true,
  },
  {
    id: 'pepino',
    name: 'Pepino',
    emoji: '🥒',
    nutrient: 'Hidratación y vitaminas',
    season: 'verano',
    points: 100,
  },
  {
    id: 'lechuga',
    name: 'Lechuga',
    emoji: '🥬',
    nutrient: 'Folatos y agua',
    season: 'primavera',
    points: 100,
  },
  {
    id: 'arvejas',
    name: 'Arvejas',
    emoji: '🫛',
    nutrient: 'Proteínas vegetales',
    season: 'primavera',
    points: 100,
  },
  {
    id: 'uva',
    name: 'Uva',
    emoji: '🍇',
    nutrient: 'Antioxidantes',
    season: 'otono',
    points: 100,
  },
];

/**
 * Spoiled product variants used by the spawn system.
 * These are visually deteriorated versions of normal products — they cost a life
 * when captured and display a non-punitive message.
 */
export const SPOILED_ITEMS: ProductConfig[] = [
  {
    id: 'manzana-podrida',
    name: 'Manzana podrida',
    emoji: '🍎',
    nutrient: 'Producto en mal estado',
    season: 'all',
    points: 0,
  },
  {
    id: 'banana-marchita',
    name: 'Banana marchita',
    emoji: '🍌',
    nutrient: 'Producto en mal estado',
    season: 'all',
    points: 0,
  },
  {
    id: 'zanahoria-golpeada',
    name: 'Zanahoria golpeada',
    emoji: '🥕',
    nutrient: 'Producto en mal estado',
    season: 'all',
    points: 0,
  },
  {
    id: 'tomate-deteriorado',
    name: 'Tomate deteriorado',
    emoji: '🍅',
    nutrient: 'Producto en mal estado',
    season: 'all',
    points: 0,
  },
];
